name: build

on:
  push:
    tags: ["*"]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release
    - name: zip release
      run: zip -j noumead-linux.zip ./target/release/noumead
    - uses: actions/upload-artifact@v3
      with:
        name: noumead-linux.zip
        path: noumead-linux.zip
  
  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build release
        run: cargo build --release
      - name: zip release
        run: zip -j noumead-osx.zip ./target/release/noumead
      - uses: actions/download-artifact@v3
        with:
          name: noumead-linux.zip
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            noumead-linux.zip
            noumead-osx.zip
